config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "locations#index"

  resources :locations do 
    resources :devices
  end

  get "/devices/:id", to: "devices#show"
  post "/devices/add_data_points", to: "data_points#create_many"

  resources :device_models

  resources :data_point_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_point.rb
class DataPoint < ApplicationRecord
  belongs_to :data_point_type
  belongs_to :device
end

app/models/data_point_type.rb
class DataPointType < ApplicationRecord
  has_many :observables, dependent: :delete_all
  has_many :device_models, through: :observables, dependent: :delete_all
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :location
  has_many :data_points
end

app/models/device_model.rb
class DeviceModel < ApplicationRecord
  has_many :observables
  has_many :data_point_types, through: :observables
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :devices, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/observable.rb
class Observable < ApplicationRecord
  belongs_to :data_point_type
  belongs_to :device_model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_point_types_controller.rb
class DataPointTypesController < ApplicationController
  def index
    @data_point_types = DataPointType.all
  end
  def show
    @data_point_type = DataPointType.find(params[:id])
  end
  def new
    @data_point_type = DataPointType.new
  end 
  def create
    @data_point_type = DataPointType.new(data_point_type_params)


    if @data_point_type.save
      redirect_to @data_point_type
    else
      render :new
    end
  end


  def edit
    @data_point_type = DataPointType.find(params[:id])
  end

  def update
    @data_point_type = DataPointType.find(params[:id])

    if @data_point_type.update(data_point_type_params)
      redirect_to @data_point_type
    else
      render :edit
    end
  end
    
  def destroy
    @data_point_type = DataPointType.find(params[:id])
    @data_point_type.destroy

    redirect_to root_path
  end

  
  private
    def data_point_type_params
      params.require(:data_point_type).permit(:name, :description)
    end
end

app/controllers/data_points_controller.rb
class DataPointsController < ApplicationController
  skip_before_action :verify_authenticity_token # XXX https://stackoverflow.com/q/23773730/5599687

  def index
  end
  
  def create_many
    params[:_json].each do |param_obj|
      @device = Device.find_by name: param_obj[:device_name]
      param_obj[:data_point_type_id] = (DataPointType.find_by name: param_obj[:data_point_type_name]).id
      @data_point = @device.data_points.create(device_id: @device.id,
                                               data_point_type_id: param_obj[:data_point_type_id],
                                               value: param_obj[:value]
                                              )
    end
    redirect_to locations_path
  end
  
end

app/controllers/device_models_controller.rb
class DeviceModelsController < ApplicationController
  def index
    @device_models = DeviceModel.all
  end
  def show
    @device_model = DeviceModel.find(params[:id])
  end
  def new
    @device_model = DeviceModel.new
  end 
  def create
    @device_model = DeviceModel.new(device_model_params)

    if @device_model.save
      params[:device_model][:data_point_type_ids].each do |data_point_type_id|
        if data_point_type_id != ""
        then @device_model.observables.create(data_point_type: DataPointType.find(data_point_type_id))
        end
      end
      redirect_to @device_model
    else
      render :new
    end
  end


  def edit
    @device_model = DeviceModel.find(params[:id])
  end

  def update
    @device_model = DeviceModel.find(params[:id])

    if @device_model.update(device_model_params)
      redirect_to @device_model
    else
      render :edit
    end
  end
    
  def destroy
    @device_model = DeviceModel.find(params[:id])
    @device_model.destroy

    redirect_to device_models_path
  end

  
  private
    def device_model_params
      params.require(:device_model).permit(:name, :description)
    end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def show
    @device = Device.find(params[:id])
  end
  def create
    @location = Location.find(params[:location_id])
    @device = @location.devices.create(name: params[:device][:name],
                                       model: params[:device][:model],
                                       device_model_id: DeviceModel.find(params[:device][:model]).id
                                      )
    redirect_to location_path(@location)
  end

  def destroy
    @location = Location.find(params[:location_id])
    @device = @location.devices.find(params[:id])
    @device.destroy
    redirect_to location_path(@location)
  end

  def edit
    @location = Location.find(params[:location_id])
    @device = @location.devices.find(params[:id])
  end

  def update
    @location = Location.find(params[:location_id])
    @device = @location.devices.find(params[:id])

    if @device.update(device_params)
      redirect_to location_path(@location)
    else
      render location_path(@location)
    end
  end
    
  

  private
    def device_params
      params.require(:device).permit(:name, :model)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout 'application'
  def index
    @locations = Location.all
  end
  def show
    @location = Location.find(params[:id])
  end
  def new
    @location = Location.new
  end 
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render :new
    end
  end


  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      redirect_to @location
    else
      render :edit
    end
  end
    
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to root_path
  end

  
  private
    def location_params
      params.require(:location).permit(:name, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_point_helper.rb
module DataPointHelper
end

app/helpers/data_point_type_helper.rb
module DataPointTypeHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/data_point/index.html.erb
<h1>DataPoint#index</h1>
<p>Find me in app/views/data_point/index.html.erb</p>

app/views/data_point_types/_data_point_type.html.erb
<p>
<strong><%= data_point_type.name %></strong> [<%= data_point_type.unit %>]

</p>

app/views/data_point_types/index.html.erb
<h1>Data Point Types</h1>

<ul>
<% @data_point_types.each do |data_point_type| %>
  <li><%= render data_point_type %></li>
<% end %>
</ul>

app/views/device_models/_form.html.erb
<%= form_with model: device_model do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% device_model.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :data_point_type_ids %> <br>
    <p><%= form.collection_check_boxes :data_point_type_ids, DataPointType.order(:name), :id, :name %></p>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/device_models/edit.html.erb
<h1>Edit Device Model</h1>

<%= render "form", device_model: @device_model %>

app/views/device_models/index.html.erb
<h1>Device Models</h1>
<p>
  <ul>
    <% @device_models.each do |device_model| %>
      <li>
        <%= link_to device_model.name, device_model %>
      </li>
    <% end %>
  </ul>
  <%= link_to "New DeviceModel", new_device_model_path %>
</p>

<hr>
<p> <%= link_to "Device Models", device_models_path %> </p>
<p> <%= link_to "Locations", locations_path %> </p>

app/views/device_models/new.html.erb
<h1>Device Model</h1>

<%= render "form", device_model: @device_model %>

app/views/device_models/show.html.erb
<h1><%= @device_model.name %></h1>

<% @device_model.observables.each do |observable| %>
  <% dpt = DataPointType.find(observable.data_point_type_id) %>
  <p><%= dpt.name %> [<%= dpt.unit %>]</p>
<% end %>


<ul>
  <li><%= link_to "Edit", edit_device_model_path(@device_model) %></li>
  <li><%= link_to "Destroy", device_model_path(@device_model),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<hr>
<p> <%= link_to "Device Models", device_models_path %> </p>
<p> <%= link_to "Locations", locations_path %> </p>

app/views/devices/_device.html.erb
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://d3js.org/d3.v7.min.js"></script>
  <meta http-equiv="Refresh" content="15">
</head> 

<p>
<% device_model = DeviceModel.find(device.model) %>
<p><strong><%= "(#{device.id}) #{device.name}" %></strong> (<%= device_model.name %>)</p>

<% device_model.observables.each do |observable| %>
  <% dpt = DataPointType.find(observable.data_point_type_id) %>
  <%= dpt.name %>: 
  <% @last_point = device.data_points.order(:updated_at).select {|i| i.data_point_type_id == observable.data_point_type_id}.last %>
  last value = <%= @last_point.value if @last_point %> <%= dpt.unit %>

  <p>

  <!-- see https://stackoverflow.com/a/24456817/5599687 -->
  <% @data_string = %Q[{"data": ]+"["+device.data_points.select {|i| i.data_point_type_id == dpt.id}.last(50).map {|x| %Q[{"x": #{x.updated_at.to_i}, "t": "#{x.updated_at.strftime("%Y-%m-%d %H:%M:%S")}", "y": #{x.value}}] }.to_sentence(two_words_connector: ",", last_word_connector: ",")+"]"+%Q[, "observable": {"name": "#{dpt.name}", "unit": "#{dpt.unit}"}}] %>
  <div id="scatter_area_<%= dpt.name %>"></div>

  <%= javascript_tag do %>

  // set the dimensions and margins of the graph
  var margin = {top: 10, right: 40, bottom: 30, left: 30},
    width = window.innerWidth - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

  // append the svg object to the body of the page
  var svg_obj = d3.select("#scatter_area_<%= dpt.name %>")
    .append("svg")
      .attr("width", width )
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform",
            "translate(" + margin.left + "," + margin.top + ")");

  //data_object = JSON.parse($("#data_plot_<%= dpt.name %>").attr('data_plot'))
  data_object = JSON.parse(<%= @data_string.to_json.html_safe %>)
  console.log(data_object)

  all_points = data_object.data //data_object.reduce((pre, cur, idx) => [...pre, ...cur.data], Array())
  times = all_points.map(d=>Date.parse(d.t))
  min_x = times.reduce((pre, cur) => Math.min(pre, cur), Number.POSITIVE_INFINITY)
  max_x = times.reduce((pre, cur) => Math.max(pre, cur), Number.NEGATIVE_INFINITY)
  min_y = all_points.reduce((pre, cur) => Math.min(pre, cur.y), Number.POSITIVE_INFINITY)
  max_y = all_points.reduce((pre, cur) => Math.max(pre, cur.y), Number.NEGATIVE_INFINITY)

  var x = d3.scaleLinear()
    .domain([min_x, max_x])
    .range([0, width]);
  var t_scale = d3.scaleTime()
    .domain([new Date(min_x), new Date(max_x)])
    .range([0, width]);
t_scale.ticks(10).map(d3.utcFormat("%I %p"))
  svg_obj
    .append('g')
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(t_scale));
  
  var y = d3.scaleLinear()
      .domain([min_y, max_y])
      .range([height, 0]);
  svg_obj
    .append('g')
    .call(d3.axisLeft(y));
    
  svg_obj
    .append('g')
    .selectAll("whatever")
    .data(data_object.data)
    .join("circle")
    .attr("cx", function(d){ return t_scale(new Date(Date.parse(d.t))) })
    .attr("cy", function(d){ return y(d.y) })
    .attr("r", 5);
  
  
  <% end %>
<% end %>

</p>

<p>
  <%= link_to 'Destroy Device', [device.location, device],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
</p>

app/views/devices/_form.html.erb
<%= form_with model: [ @location, @location.devices.build ] do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :model %><br>
    <%= form.collection_select :model, DeviceModel.order(:name), :id, :name %>
  </div>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/devices/show.html.erb
<%= render @device %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script> 

<html>
  <head>
    <title>NtuityAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="p-1 text-center">
    <h2>Ntuity Assignment</h2>
  </div>


  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Device Models", device_models_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <p> <%= link_to "Locations", locations_path, :class => 'nav-link' %> </p>
      </li>
    </ul>
  </div>
</nav>


  <body>
    <%= yield %>
  </body>

  <footer>

  </footer>
</html>

app/views/locations/_form.html.erb
<%= form_with model: location do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% location.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% location.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render "form", location: @location %>

app/views/locations/index.html.erb
 <div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <h1>Locations</h1>
    </div>
    <div class="col-md-3">
      <%= button_to "New Location", new_location_path, method: :get, class: 'btn btn-outline-primary' %>
    </div>
  </div>
</div>
<p>
  <ul>
    <% @locations.each do |location| %>
      <li>
        <%= link_to location.name, location %>: <%= location.description %>
      </li>
    <% end %>
  </ul>
</p>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render "form", location: @location %>

app/views/locations/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <h1><%= @location.name %></h1>
    </div>
    <div class="col-md-3">
      <nav class="navbar navbar-expand-sm">
        <div class="container-fluid">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Edit", edit_location_path(@location), class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <p> <%= link_to "Destroy", location_path(@location),
                method: :delete,
                data: { confirm: "Are you sure?" }, :class => 'nav-link' %> </p>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>
<div>
  <h3><%= @location.description %></h3>



<h2>Devices</h2>
<%= render @location.devices %>

<h2>Add a device:</h2>
<%= render 'devices/form' %>

</div>